// Generated by CoffeeScript 1.12.7
(function() {
  window.test = function(fontFamily, fontSize, fontWeight, drawSmartUnderlines) {
    var _, ascenderHeight, baselineY, canvasWrapDiv, canvasWrapOuterDiv, capHeight, descenderHeight, descenderY, domTextDiv, fontSizeInt, lineHeightInt, metrics, ref, resultsParagraph, smartUnderlinePosition, smartUnderlinePositionPercent, smartUnderlineResult, testDiv, testId, testString, testTitle, textHeight, textWidth, xHeight;
    ref = Typography.evaluate(fontFamily, fontSize, fontWeight), baselineY = ref.baselineY, xHeight = ref.xHeight, capHeight = ref.capHeight, ascenderHeight = ref.ascenderHeight, descenderHeight = ref.descenderHeight, _ = ref._;
    testId = fontFamily + " " + fontSize + " " + fontWeight;
    testString = (fontFamily.replace(/\"/g, "")) + " Ixgh";
    fontSizeInt = parseInt(fontSize, 10);
    lineHeightInt = fontSizeInt * 1.4;
    testDiv = document.createElement('div');
    testDiv.className = 'test';
    testDiv.setAttribute('data-test-id', testId);
    domTextDiv = document.createElement('div');
    domTextDiv.className = 'dom-text';
    domTextDiv.textContent = testString;
    domTextDiv.style.fontSize = fontSize;
    domTextDiv.style.fontWeight = fontWeight;
    domTextDiv.style.fontFamily = fontFamily;
    canvasWrapDiv = document.createElement('div');
    canvasWrapDiv.className = 'canvas-wrap';
    canvasWrapDiv.appendChild(_.canvas);
    canvasWrapDiv.appendChild(domTextDiv);
    canvasWrapOuterDiv = document.createElement('div');
    canvasWrapOuterDiv.className = 'canvas-wrap-outer';
    canvasWrapOuterDiv.style.minHeight = lineHeightInt + "px";
    canvasWrapOuterDiv.appendChild(canvasWrapDiv);
    testTitle = document.createElement('h2');
    testTitle.textContent = fontSize + " " + fontWeight;
    resultsParagraph = document.createElement('p');
    resultsParagraph.textContent = "baselineY      " + baselineY + "\nxHeight        " + xHeight + "\ncapHeight      " + capHeight + "\nascenderHght   " + ascenderHeight + "\ndescenderHght  " + descenderHeight;
    metrics = _.context.measureText(testString);
    textWidth = metrics.width;
    _.canvas.width = textWidth;
    Typography.normalizeContext(_.context);
    _.context.font = fontWeight + " " + fontSize + "/normal " + fontFamily;
    _.context.fillStyle = '#a0a0a0';
    _.context.fillRect(0, 0, _.canvas.width, 1);
    _.context.fillStyle = 'red';
    _.context.fillRect(0, baselineY, _.canvas.width, 1);
    _.context.fillStyle = 'orange';
    _.context.fillRect(0, baselineY - xHeight, _.canvas.width, 1);
    _.context.fillStyle = 'purple';
    _.context.fillRect(0, baselineY - capHeight, _.canvas.width, 1);
    _.context.fillStyle = 'green';
    _.context.fillRect(0, baselineY - ascenderHeight, _.canvas.width, 1);
    _.context.fillStyle = 'blue';
    _.context.fillRect(0, baselineY + descenderHeight, _.canvas.width, 1);
    _.context.fillStyle = 'red';
    _.context.fillText(testString, 0, metrics.fontBoundingBoxAscent || 0);
    testDiv.appendChild(canvasWrapOuterDiv);
    testDiv.appendChild(testTitle);
    testDiv.appendChild(resultsParagraph);
    if (ascenderHeight < capHeight || capHeight < xHeight) {
      testDiv.classList.add('fail');
    }
    if (baselineY <= 0 || xHeight <= 0 || capHeight <= 0 || ascenderHeight <= 0 || descenderHeight <= 0) {
      testDiv.classList.add('fail');
    }
    if (baselineY > lineHeightInt || xHeight > lineHeightInt || capHeight > lineHeightInt || ascenderHeight > lineHeightInt || descenderHeight > lineHeightInt) {
      testDiv.classList.add('fail');
    }
    results.appendChild(testDiv);
    if (drawSmartUnderlines) {
      testDiv.classList.add('with-smart-underline');
      textHeight = domTextDiv.getClientRects()[0].height - 1;
      descenderY = baselineY + descenderHeight;
      smartUnderlinePosition = Math.max(((descenderY - baselineY) / 2) + 1, 3) + baselineY;
      if (descenderHeight === 3) {
        smartUnderlinePosition = baselineY + descenderHeight;
      }
      smartUnderlinePositionPercent = Math.round(100 * smartUnderlinePosition / textHeight);
      if (descenderHeight > 2 && fontSizeInt > 10 && smartUnderlinePositionPercent <= 100) {
        domTextDiv.style.textShadow = '0.03em 0 #fff, -0.03em 0 #fff, 0 0.03em #fff, 0 -0.03em #fff, 0.06em 0 #fff, -0.06em 0 #fff, 0.09em 0 #fff, -0.09em 0 #fff, 0.12em 0 #fff, -0.12em 0 #fff, 0.15em 0 #fff, -0.15em 0 #fff';
        domTextDiv.style.backgroundImage = 'linear-gradient(#fff, #fff), linear-gradient(#fff, #fff), linear-gradient(#000, #000)';
        domTextDiv.style.backgroundImage = 'linear-gradient(#fff, #fff), linear-gradient(#fff, #fff), linear-gradient(#000, #000)';
        domTextDiv.style.backgroundSize = '0.05em 1px, 0.05em 1px, 1px 1px';
        domTextDiv.style.backgroundRepeat = 'no-repeat, no-repeat, repeat-x';
        domTextDiv.style.backgroundPosition = "0% " + smartUnderlinePositionPercent + "%, 100% " + smartUnderlinePositionPercent + "%, 0% " + smartUnderlinePositionPercent + "%";
        smartUnderlineResult = document.createElement('p');
        smartUnderlineResult.innerHTML = "underlinePosY  " + smartUnderlinePositionPercent + "%";
        return testDiv.appendChild(smartUnderlineResult);
      } else {
        return domTextDiv.style.textDecoration = 'underline';
      }
    }
  };

  window.testSuite = function() {
    var fontFamilies, fontFamily, i, len, results1, size, sizes;
    fontFamilies = ['Arial', 'Futura', 'Georgia', '"Gill Sans"', 'Helvetica', '"Helvetica Neue"', 'monospace', 'sans-serif', 'serif', 'Times', '"Times New Roman"'];
    sizes = ['36px', '24px', '16px', '16px', '8px'];
    results1 = [];
    for (i = 0, len = sizes.length; i < len; i++) {
      size = sizes[i];
      results1.push((function() {
        var j, len1, results2;
        results2 = [];
        for (j = 0, len1 = fontFamilies.length; j < len1; j++) {
          fontFamily = fontFamilies[j];
          test(fontFamily, size, 'normal');
          if (size === '16px') {
            results2.push(test(fontFamily, size, 'bold'));
          } else {
            results2.push(void 0);
          }
        }
        return results2;
      })());
    }
    return results1;
  };

  window.testFontsInSizeRange = function(fontFamilies, smallestSize, largestSize) {
    var drawSmartUnderlines, fontFamily, i, ref, ref1, results1, size;
    if (smallestSize == null) {
      smallestSize = 8;
    }
    if (largestSize == null) {
      largestSize = 36;
    }
    if (typeof fontFamilies === 'string') {
      fontFamilies = [fontFamilies];
    }
    results1 = [];
    for (size = i = ref = largestSize, ref1 = smallestSize; ref <= ref1 ? i <= ref1 : i >= ref1; size = ref <= ref1 ? ++i : --i) {
      results1.push((function() {
        var j, len, results2;
        results2 = [];
        for (j = 0, len = fontFamilies.length; j < len; j++) {
          fontFamily = fontFamilies[j];
          results2.push(test(fontFamily, size + "px", 'normal', drawSmartUnderlines = true));
        }
        return results2;
      })());
    }
    return results1;
  };

}).call(this);
