// Generated by CoffeeScript 1.12.7
(function() {
  var calculateBoundary, clearCanvas;

  clearCanvas = function(canvas, context) {
    return context.clearRect(0, 0, canvas.width, canvas.height);
  };

  calculateBoundary = function(text, canvas, context) {
    var alpha, highestY, i, j, lowestY, metrics, pixelData, r, ref, ref1, textWidth, x, y;
    clearCanvas(canvas, context);
    context.fillStyle = 'red';
    metrics = context.measureText(text);
    textWidth = metrics.width;
    context.fillText(text, 0, metrics.fontBoundingBoxAscent || 0);
    lowestY = void 0;
    highestY = void 0;
    for (x = i = 0, ref = textWidth; 0 <= ref ? i <= ref : i >= ref; x = 0 <= ref ? ++i : --i) {
      for (y = j = 0, ref1 = canvas.height; 0 <= ref1 ? j <= ref1 : j >= ref1; y = 0 <= ref1 ? ++j : --j) {
        pixelData = context.getImageData(x, y, x + 1, y + 1);
        r = pixelData.data[0];
        alpha = pixelData.data[3];
        if (r === 255 && alpha > 50) {
          if (!lowestY) {
            lowestY = y;
          }
          if (!highestY) {
            highestY = y;
          }
          if (y < lowestY) {
            lowestY = y;
          }
          if (y > highestY) {
            highestY = y;
          }
        }
      }
    }
    clearCanvas(canvas, context);
    return {
      lowestY: lowestY,
      highestY: highestY
    };
  };

  window.Typography = {
    evaluate: function(fontFamily, fontSize, fontWeight) {
      var ascenderHeight, baselineY, canvas, capHeight, context, descenderHeight, highestY, lowestY, ref, ref1, xHeight;
      canvas = document.createElement('canvas');
      context = canvas.getContext('2d');
      canvas.height = canvas.width = parseInt(fontSize, 10) * 1.4;
      Typography.normalizeContext(context);
      context.font = fontWeight + " " + fontSize + "/normal " + fontFamily;
      ref = calculateBoundary('I', canvas, context), lowestY = ref.lowestY, highestY = ref.highestY;
      baselineY = highestY;
      capHeight = baselineY - lowestY;
      lowestY = calculateBoundary('x', canvas, context).lowestY;
      xHeight = baselineY - lowestY;
      highestY = calculateBoundary('g', canvas, context).highestY;
      descenderHeight = highestY - baselineY;
      ref1 = calculateBoundary('h', canvas, context), lowestY = ref1.lowestY, highestY = ref1.highestY;
      ascenderHeight = baselineY - lowestY;
      ascenderHeight = Math.max(ascenderHeight, capHeight);
      return {
        baselineY: baselineY,
        xHeight: xHeight,
        capHeight: capHeight,
        ascenderHeight: ascenderHeight,
        descenderHeight: descenderHeight,
        _: {
          canvas: canvas,
          context: context
        }
      };
    },
    normalizeContext: function(context) {
      context.textBaseline = 'top';
      context.textAlign = 'start';
      context.fontStretch = 1;
      return context.angle = 0;
    }
  };

}).call(this);
